### ISSUE TITLE
Correction to Step 5?

### ISSUE THREAD

**Issue by JofArnold** [weijiekoh/zkmm#2]
Should Step 5 validate in JS be this?

```
node --max-old-space-size=4000 build/mastermind/src/test_js_verification.js \
  -c mastermind/circuits/mastermind.json \
  -vk mastermind/setup/mastermind.vk.json \
  -p mastermind/proofs/mastermind.proof.json \
  -s mastermind/signals/testsignals.json
  ```
  
  Otherwise you get this error
  
  ```
  ➜  zkmm git:(master) ✗  node --max-old-space-size=4000 build/mastermind/src/test_js_verification.js \
  -c mastermind/circuits/mastermind.json \
  -vk mastermind/setup/mastermind.vk.json \
  -pk mastermind/setup/mastermind.pk.json \
  -s mastermind/signals/testsignals.json
usage: test_js_verification.js [-h] -c CIRCUIT -vk VERIFYING_KEY -p PROOF -s
                               SIGNALS

test_js_verification.js: error: Unrecognized arguments: mastermind/setup/mastermind.pk.json
```
 
 Whereas using the commands I give you get, for instance
 
 ```
 2021-10-16T13:41:22.725Z 'Loading circuit'
2021-10-16T13:41:22.729Z 'Calculating witness'
Hash calculated by JS     : 6907462941185715570254759478774396641147731893488145170844721712986253285833
Hash calculated by circuit: 6907462941185715570254759478774396641147731893488145170844721712986253285833
2021-10-16T13:41:22.871Z 'Verifying proof'
2021-10-16T13:41:23.478Z 'Done'
The proof is valid
```

**Comment by JofArnold** [comment]
My mistake. Was looking at wrong section

**Comment by weijiekoh** [comment]
FWIW this entire repository is outdated and I strongly recommend rewriting everything using modern tooling:

- snarkjs 0.4.x
- circom v2
- Poseidon hash instead of Pedersen
- Also, I wrote the circuit when I was starting out learning circom so it's probably poorly written and even insecure...

**Comment by JofArnold** [comment]
Hey, thanks for the message. Actually it's super useful having something out of date because there's the basic principles but I have to convert it all to newer code so I get to learn a lot fixing things along the way.

I'm working working with snarkjs and circom 2 already but I'm wondering; why Poseidon rather than Pedersen? I'm not really familiar with those aspects yet... Still doing a lot of studying of the principles.

Also totally cool about it being early! And I'm super grateful you put this code out even so. I'm just starting in the field and have just pushed a monorepo where I'm going to be learning a lot of stuff in public too https://github.com/JofArnold/zkp-learning-in-public :)

**Comment by weijiekoh** [comment]
Hi! Happy to help!

Check out the @real_crypt channel on Telegram, where the auditor of Tornado Cash states "We do not recommend using Pedersen hash in protocols and applications."

I have not looked deeply into whether his criticisms of Pedersen hash are valid with regards to this application. though in the Tornado Cash audit, he states that they used Pedersen hash correctly.

Poseidon, in contrast, is pretty straightforward to use, so one might as well just do so.

Please feel free to DM if you have any other questions :)
